language: cpp

sudo: false
dist: precise
group: legacy

os:
  - linux

compiler:
  - gcc

git:
  depth: 30

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - cmake-data
    - python
    - libboost-thread-dev
    - libboost-random-dev
    - libboost-system-dev
    - libboost-filesystem-dev
    - libboost-test-dev
    - libboost-python-dev
    - freeglut3-dev
    - libxmu-dev
    - libxi-dev
    - swig
    - libpng-dev
    - libjpeg-dev
    - libxxf86vm1
    - libxxf86vm-dev
    - libxi-dev
    - libxrandr-dev
    - mesa-common-dev
    - mesa-utils-extra
    - libgl1-mesa-dev
    - libglapi-mesa
    - libgtk-3-dev
    - tree
    - gcc-5
    - g++-5

cache: 
  apt: true
  directories:
  - $HOME/wxWidgets-install

notifications:
  email: false
#     recipients:
#       - "i-simpa@ifsttar.fr"

before_install:
  - ./ci/travis/${TRAVIS_OS_NAME}/before_install.sh

install:
  - ./ci/travis/${TRAVIS_OS_NAME}/install.sh

before_script:
  - ./ci/travis/${TRAVIS_OS_NAME}/before_script.sh

script:
  - ./ci/travis/${TRAVIS_OS_NAME}/script.sh

after_script:
  - ./ci/travis/${TRAVIS_OS_NAME}/after_script.sh
