
# specify custom environment variables
environment:
  matrix:
    - VisualStudioVersion: 14.0
      platform: "Win64"
      configuration: "Release"
      vcvarsall_platform: "x64"
  P: C:\projects\isimpax64
  global:
    MSVC_DEFAULT_OPTIONS: ON
    BOOST_ROOT: C:\Libraries\boost_1_60_0
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib64-msvc-14.0
    PYTHON_LIBRARY: C:\Python27-x64\libs\python27.lib
    PYTHON_INCLUDE_DIR: C:\Python27-x64\include
    WXWIN: C:\wxWidgets-3.1.0\
    wxWidgets_ROOT_DIR: C:\wxWidgets-3.1.0\
    wxWidgets_INCLUDE_DIRS: C:\wxWidgets-3.1.0\include
    wxWidgets_LIBRARIES: C:\wxWidgets-3.1.0\lib\vc140_dll
    SWIG_DIR: C:\Libraries\swigwin-3.0.11
    SWIG_EXECUTABLE: C:\Libraries\swigwin-3.0.11\swig.exe    
    
# branches to build
branches:
  # whitelist
  only:
    - master

# Operating system (build VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input


# clone directory
clone_folder: c:\projects\isimpa

platform: x64
configuration: Release

install:
  # by default, all script lines are interpreted as batch

build:
  project: c:\projects\isimpax64\isimpa.sln      # path to Visual Studio solution or project

# scripts to run before build
before_build:
  - ps: git rev-parse HEAD
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
  # sent environment variables for wxWidgets
  - set WXWIN=C:\wxWidgets-3.1.0\
  - set wxWidgets_ROOT_DIR=%WXWIN%
  - set wxWidgets_LIB_DIR=%WXWIN%\lib\vc_dll
  - echo Download wxWidgets lib
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.0/wxWidgets-3.1.0.7z'
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.0/wxMSW-3.1.0_vc140_Dev.7z'
  - cmd: 7z x wxWidgets-3.1.0.7z -oC:\wxWidgets-3.1.0
  - cmd: 7z x wxMSW-3.1.0_vc140_Dev.7z -oC:\wxWidgets-3.1.0
  - cmd: dir %wxWidgets_LIBRARIES%
  # install dependencies:
  - choco install poedit nsis
  - ps: Start-FileDownload 'https://kent.dl.sourceforge.net/project/swig/swigwin/swigwin-3.0.11/swigwin-3.0.11.zip' -FileName 'c:\Libraries\swigwin-3.0.11.zip' -Timeout 15000 
  - ps: 7z x c:\Libraries\swigwin-3.0.11.zip -oC:\Libraries -r -y
  - cmd: SET PATH=%PATH%;%WXWIN%;%SWIG_DIR%;%wxWidgets_LIB_DIR%;C:\Program Files (x86)\Poedit\Gettexttools\bin;
  - ps: swig.exe -version
  - echo Running cmake...
  - cmd: mkdir C:\projects\isimpax64
  - cmd: cd C:\projects\isimpax64
  - cmd: echo wxWidgets_CONFIGURATION:STRING=mswu > CMakeCache.txt
  - cmd: echo wxWidgets_LIB_DIR:PATH=%wxWidgets_LIBRARIES% >> CMakeCache.txt
  - cmd: echo wxWidgets_ROOT_DIR:PATH=%wxWidgets_ROOT_DIR% >> CMakeCache.txt
  - cmd: echo WX_LIB_DIR:INTERNAL=%wxWidgets_LIBRARIES% >> CMakeCache.txt
  - cmd: echo WX_ROOT_DIR:INTERNAL=%wxWidgets_ROOT_DIR% >> CMakeCache.txt
  - cmake --debug-output -G "Visual Studio 14 2015 Win64" c:\projects\isimpa

build_script:
  - cd c:\projects\isimpax64
  - ECHO Building %configuration% %platform% with MSVC %VisualStudioVersion% using %PlatformToolset% PlatformToolset
  - dir
  - 'CALL "C:\Program Files (x86)\Microsoft Visual Studio %VisualStudioVersion%\VC\vcvarsall.bat" %vcvarsall_platform%'
  - msbuild "isimpa.sln" /consoleloggerparameters:Verbosity=minimal /target:Build /property:Configuration="%configuration%";Platform=%platform% /p:PlatformToolset=%PlatformToolset% /maxcpucount /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

  
artifacts:
  - path: 'c:\projects\isimpax64\*.exe'
    name: isimpa-win64
  - path: 'c:\projects\isimpax64\CMakeFiles\CMakeOutput.log'
    name: cmake_output_log
  - path: 'c:\projects\isimpax64\CMakeFiles\CMakeError.log'
    name: cmake_output_log
  
  
  