
# specify custom environment variables
environment:
  P: "c:/projects/isimpax64"
  global:
    MSVC_DEFAULT_OPTIONS: ON
    BOOST_ROOT: C:\Libraries\boost_1_60_0
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib64-msvc-14.0
    PYTHON_LIBRARY: C:\Python27-x64
    PYTHON_INCLUDE_DIR: C:\Python27-x64\include
    wxWidgets_ROOT_DIR: C:\Libraries\wxWidgets
    wxWidgets_INCLUDE_DIRS: C:\Libraries\wxWidgets\include
    wxWidgets_LIBRARIES: C:\Libraries\wxWidgets\lib\vc140_dll
    
# branches to build
branches:
  # whitelist
  only:
    - master

# Operating system (build VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input


# clone directory
clone_folder: c:\projects\isimpa

platform: x64
configuration: Release

install:
  # by default, all script lines are interpreted as batch

build:
  project: %P%\INSTALL.vcxproj      # path to Visual Studio solution or project

# scripts to run before build
before_build:
  - echo Download wxWidgets lib  
  - $source = "https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.0/wxMSW-3.1.0_vc140_Dev.7z"
  - $destination = "c:\Libraries\wxMSW-3.1.0_vc140_Dev.7z"
  - Invoke-WebRequest $source -OutFile $destination
  - 7z x $destination -oC:\Libraries\wxWidgets -r -y
  - $source = https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.0/wxWidgets-3.1.0.7z
  - $destination = "c:\Libraries\wxWidgets-3.1.0.7z"
  - Invoke-WebRequest $source -OutFile $destination
  - 7z x $destination -oC:\Libraries\wxWidgets -r -y
  - echo Running cmake...
  - cd c:\projects\isimpa
  - cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_INSTALL_PREFIX=%P%
  
artifacts:
  - path: *.exe
    name: isimpa-win64
  
  
  