
# specify custom environment variables
environment:
  P: "c:/projects/isimpax64"
  global:
    MSVC_DEFAULT_OPTIONS: ON
    BOOST_ROOT: C:\Libraries\boost_1_60_0
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_60_0\lib64-msvc-14.0
    PYTHON_LIBRARY: C:\Python27-x64
    PYTHON_INCLUDE_DIR: C:\Python27-x64\include
    SWIG_DIR: C:\Libraries\swigwin-3.0.11
    SWIG_EXECUTABLE: C:\Libraries\swigwin-3.0.11\swig.exe
    
# branches to build
branches:
  # whitelist
  only:
    - master

# Operating system (build VM template)
os: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
init:
  - git config --global core.autocrlf input


# clone directory
clone_folder: c:\projects\isimpa

platform: x64
configuration: Release

install:
  # by default, all script lines are interpreted as batch

build:
  project: c:\projects\isimpax64\INSTALL.vcxproj      # path to Visual Studio solution or project

# scripts to run before build
before_build:
  - echo Download wxWidgets lib
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.0/wxWidgets-3.1.0.7z'
  - ps: Start-FileDownload 'https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.0/wxMSW-3.1.0_vc140_Dev.7z'
  - cmd: 7z x wxWidgets-3.1.0.7z -oC:\wxWidgets
  - cmd: 7z x wxMSW-3.1.0_vc140_Dev.7z -oC:\wxWidgets
  - echo Download SWIG
  - ps: Start-FileDownload 'https://kent.dl.sourceforge.net/project/swig/swigwin/swigwin-3.0.11/swigwin-3.0.11.zip' -FileName 'c:\Libraries\swigwin-3.0.11.zip' -Timeout 15000 
  - ps: 7z x c:\Libraries\swigwin-3.0.11.zip -oC:\Libraries -r -y
  - ps: C:\Libraries\swigwin-3.0.11\swig.exe -version
  - echo Running cmake...
  - cd c:\projects\isimpa
  - cmake -G "Visual Studio 14 2015 Win64" -DCMAKE_INSTALL_PREFIX=%P% -DSWIG_DIR="%SWIG_DIR%" -DSWIG_EXECUTABLE="%SWIG_EXECUTABLE%" -DPYTHON_LIBRARY="%PYTHON_LIBRARY%" -DPYTHON_INCLUDE_DIR="%PYTHON_INCLUDE_DIR%"
  
artifacts:
  - path: 'c:\projects\isimpax64\*.exe'
    name: isimpa-win64
  
  
  